### ISSUE TITLE
After Effects Script not working on Adobe CC (Win7)

### ISSUE THREAD

**Issue by SimonHoe** [paazmaya/creative-suite-to-qml#1]
Hi,
 the Photoshop script is working just fine, but I couldn't get the After Effects script to work. When I press 
 "Start Processing" the dialog window just disappears. It creates a qml file which is empty.

I'm on a windows 7 machine using After Effects CC. I also tried CS6 and CS5.5, but that also didn't work. Any idea what might be the problem? For which version of After Effects was the script originally written?

Your help would be much appreciated!

Regards
Simon

**Comment by ericblade** [comment]
Hi Simon

It would be nice if there were some more detailed instructions on how to actually make use of this :-)

After getting the same results you did, I went to see if there were any other similar things.. and I found a AE to HTML converter.. which had instructions that point to going into Settings in AE, and there's a checkbox that you have to tick to "Allow scripts to write to files".

I'm not sure why it's able to create a 0-byte file if it's not allowed to write to files, but I guess Adobe does things differently than the rest of the world.  (as if I didn't already know that)

SO, you need to do that to get the AE to QML converter to work.

At least then you end up with some runnable QML.  I haven't really made a lot of sense out of it, but it's slightly better for QML engineers to follow along with it, than with videos rendered from AE :D 

When you do get it working, if you come up with any other tips, please drop me a line :-)

**Comment by paazmaya** [comment]
Great finding @ericblade, I will mention the configuration options in the documentation...

**Comment by SimonHoe** [comment]
Hi Eric,
thank you very much for your reply. That did the trick. 

I also don't know yet how to make use of it. There was no explanation about the actual functionality and the output.  

I was hoping to get the transition information in code form for the animations I did in After Effects. For example how the opacity or position/rotation of some elements change over time. Otherwise you have to create these changes in Qt on your own, even though they were already done in AE.

After my first test it seems to output these values. But instead of the actual pictures/elements used in AE it replaces them with Rectangles and applies the transitions. Would have been nice if it would somehow export the layers as pictures as well. Now I have to find out how it does the animations in Qt and then combine it with the output from the Photoshop script.

**Comment by ericblade** [comment]
paazmaya: awesome.  Can you perhaps shed some light on how you go about making use of the scripts?  Perhaps it's just the input that the AE designers I was working with gave it as a test, but I basically just ended up with a bunch of full-screen rectangles that performed an animation that looked sort of like the original, if given a good imagination :-)  it was really quite difficult to see what was going on.. so I'm wondering if there's some additional steps that should be performed for preparing things, or other good practices when creating the AE things.

**Comment by paazmaya** [comment]
The purpose of the script was to transfer only the transitions over to QML and use rectangles, which should have the same size as the moved elements.
In case the elements in AE are full screen, then the rectangles are that too...

Anyhow it has been few years when I last time used the script and it might be that the AE API has changed somehow....

**Comment by ericblade** [comment]
ah, ok, that makes sense, then.  The AE users had just put together a quick test so that we could see how to get the script to work to begin with.

It's going to be probably at least a week or two before I have the opportunity to mess with it with our real AE files.. I'm hoping that it will at least give us useful output to begin with, and then maybe after we're done with our current deadlines, we can maybe implement any ideas we might've had.  Of course, I'll share. :-)
